services:
   proxy-reverso: 
    image: proxy-reverso
    container_name: proxy-reverso
    networks:
      - fcnet
    ports:
      - "8080:80"
    build:
      dockerfile: ./Nginx.Dockerfile

   site: 
    image: conteudo-site-node
    container_name: site
    networks:
      - fcnet
    build:
      dockerfile: ./Node.Dockerfile
    volumes:
      - ./node:/usr/src

   db: 
    image: mysql
    command: --innodb-use-native-aio=0
    container_name: banco-de-dados
    tty: true
    restart: always
    environment:
      - MYSQL_USER=matheus
      - MYSQL_PASSWORD=admin
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=dados
    volumes:
      - ./mysql:/var/lib/mysql
      - ./mysql-migrations/:/docker-entrypoint-initdb.d/
    networks:
      - fcnet
    expose:
      - 3306

networks:
   fcnet:
    driver: bridge 